FROM node:22-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

RUN npm run build

FROM node:22-alpine

RUN npm install -g serve@latest

COPY --from=builder /app/dist /app/dist

ENV PORT=3000
EXPOSE ${PORT}

CMD sh -c "serve -s /app/dist -l ${PORT}"
